### ISSUE TITLE
Asset's value seems not ok.

### ISSUE THREAD

**Issue by reuniware** [BifrostTitan/Philosophers-Stone#3]
When running for AAVE-USD, the following "current value" is not the real one.

04/11/2022 10:49:20 | AAVE-USD | Hourly Candle | Market Dip Detected | Current Value: $86,18877| Predicted Value: $84,47305| Change: -2%

![199944643-90301287-785c-4753-8883-85755bace261](https://user-images.githubusercontent.com/16271697/199946462-9158e1d1-f8db-4829-91f7-debcc4cf2502.png)

**Comment by BifrostTitan** [comment]
Datasets are pulled in real-time from coinbase pro. Check the .csv dataset files to see if there is something wrong with the data. What markets were your analyzing in parallel to AAVE and at what time intervals?

**Comment by BifrostTitan** [comment]
Potentially patched.
https://github.com/BifrostTitan/Philosophers-Stone/commit/d5e713138395dc8d07f92b17ed7f004fe5f39830

Fetch the latest source and see if it happens again. I swapped SOL for AAVE in the neuraltree and got clean results.
Modified the core to prevent conflicts when multiple dimensions try to use the core at the same time
